default_language_version:
  python: python3.11
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.4.0"
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: debug-statements
      - id: detect-private-key

  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: "2.7.2"
    hooks:
      - id: editorconfig-checker
        alias: ec
        args:
          - -disable-indent-size

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.0.282"
    hooks:
      - id: ruff

  - repo: https://github.com/psf/black
    rev: "23.7.0"
    hooks:
      - id: black

  - repo: https://github.com/asottile/blacken-docs
    rev: "1.15.0"
    hooks:
      - id: blacken-docs
        additional_dependencies: ["black==22.10.0"]

  - repo: https://github.com/sirosen/check-jsonschema
    rev: "0.23.3"
    hooks:
      - id: check-github-workflows

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.4.1"
    hooks:
      - id: mypy
        pass_filenames: false
        additional_dependencies:
          - typing-extensions==4.4.0
          - pytest==7.2.0
          - pydantic==1.10.2
          - hypothesis==6.61.0
          - types-setuptools==67.6.0.0
          - types-requests==2.28.11.14

  - repo: https://github.com/seddonym/import-linter
    rev: "v1.10.0"
    hooks:
      - id: import-linter
        entry: env PYTHONPATH=src lint-imports --verbose

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.0"
    hooks:
      - id: prettier
        alias: format-markdown
        types: [ markdown ]
        args:
          - --parser=markdown
          - --print-width=88
          - --prose-wrap=always

  - repo: https://github.com/mgedmin/check-manifest
    rev: "0.49"
    hooks:
      - id: check-manifest
        args: ["--no-build-isolation"]
        additional_dependencies:
          - setuptools==68.1.2
