default_language_version:
  python: python3.11
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.3.0"
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: debug-statements
      - id: detect-private-key
  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: "2.6.1"
    hooks:
      - id: editorconfig-checker
        alias: ec
        args:
          - -disable-indent-size
  - repo: https://github.com/asottile/pyupgrade
    rev: "v3.2.2"
    hooks:
      - id: pyupgrade
        name: pyupgrade[codegen,tests]
        args:
          # --py311-plus replaces assert_never import, which isn't compatible with mypy yet.
          - --py310-plus
        exclude: ^src
      - id: pyupgrade
        name: pyupgrade[src]
        args:
          - --py310-plus
        exclude: ^(codegen|tests)
  - repo: https://github.com/pycqa/autoflake
    rev: "v1.7.7"
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --remove-all-unused-imports
          - --ignore-init-module-imports
  - repo: https://github.com/pycqa/isort
    rev: "5.12.0"
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: "22.10.0"
    hooks:
      - id: black
  - repo: https://github.com/asottile/blacken-docs
    rev: "v1.12.1"
    hooks:
      - id: blacken-docs
        additional_dependencies: ["black==22.10.0"]
  - repo: https://github.com/pycqa/flake8
    rev: "5.0.4"
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
          - flake8-comprehensions
        exclude: ^tests/generated/.*
  - repo: https://github.com/sirosen/check-jsonschema
    rev: "0.19.2"
    hooks:
      - id: check-github-workflows
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.0.1"
    hooks:
      - id: mypy
        pass_filenames: false
        additional_dependencies:
          - typing-extensions==4.4.0
          - pytest==7.2.0
          - pydantic==1.10.2
          - hypothesis==6.61.0
          - types-setuptools==65.6.0.2
          - phantom-types==1.2.0
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.7.1"
    hooks:
      - id: prettier
        alias: format-markdown
        types: [ markdown ]
        args:
          - --parser=markdown
          - --print-width=88
          - --prose-wrap=always
  - repo: https://github.com/mgedmin/check-manifest
    rev: "0.48"
    hooks:
      - id: check-manifest
        args: ["--no-build-isolation"]
        additional_dependencies:
          - setuptools==65.6.3
