repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.5.0"
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: debug-statements
      - id: detect-private-key

  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: "2.7.3"
    hooks:
      - id: editorconfig-checker
        alias: ec
        args:
          - -disable-indent-size

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.3.4"
    hooks:
      - id: ruff
      - id: ruff-format

  - repo: https://github.com/asottile/blacken-docs
    rev: "1.16.0"
    hooks:
      - id: blacken-docs
        additional_dependencies: ["black==24.3.0"]

  - repo: https://github.com/sirosen/check-jsonschema
    rev: "0.28.0"
    hooks:
      - id: check-github-workflows

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.9.0"
    hooks:
      - id: mypy
        pass_filenames: false
        additional_dependencies:
          - typing-extensions==4.10.0
          - pytest==7.4.3
          - pydantic==1.10.13
          - hypothesis==6.99.12
          - types-setuptools==78.1.0.20250329
          - types-requests==2.31.0.20240311

  - repo: https://github.com/seddonym/import-linter
    rev: "v2.0"
    hooks:
      - id: import-linter
        entry: env PYTHONPATH=src lint-imports --verbose

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.1.0"
    hooks:
      - id: prettier
        alias: format-markdown
        types: [ markdown ]
        additional_dependencies:
          - "prettier@3.2.5"
        args:
          - --parser=markdown
          - --print-width=88
          - --prose-wrap=always

  - repo: https://github.com/mgedmin/check-manifest
    rev: "0.49"
    hooks:
      - id: check-manifest
        args: ["--no-build-isolation"]
        additional_dependencies:
          - setuptools==78.1.0
          - setuptools-scm==8.2.0
          - wheel==0.45.1
