"""
Generated from ``clients/src/main/resources/common/message/StreamsGroupHeartbeatResponse.json``.
"""

from dataclasses import dataclass
from dataclasses import field
from typing import ClassVar

from kio.schema.errors import ErrorCode
from kio.schema.response_header.v1.header import ResponseHeader
from kio.schema.types import TopicName
from kio.static.constants import EntityType
from kio.static.primitive import i8
from kio.static.primitive import i16
from kio.static.primitive import i32
from kio.static.primitive import i32Timedelta
from kio.static.primitive import u16


@dataclass(frozen=True, slots=True, kw_only=True)
class Status:
    __type__: ClassVar = EntityType.nested
    __version__: ClassVar[i16] = i16(0)
    __flexible__: ClassVar[bool] = True
    __api_key__: ClassVar[i16] = i16(88)
    __header_schema__: ClassVar[type[ResponseHeader]] = ResponseHeader
    status_code: i8 = field(metadata={"kafka_type": "int8"})
    """A code to indicate that a particular status is active for the group membership"""
    status_detail: str = field(metadata={"kafka_type": "string"})
    """A string representation of the status."""


@dataclass(frozen=True, slots=True, kw_only=True)
class TaskIds:
    __type__: ClassVar = EntityType.nested
    __version__: ClassVar[i16] = i16(0)
    __flexible__: ClassVar[bool] = True
    __api_key__: ClassVar[i16] = i16(88)
    __header_schema__: ClassVar[type[ResponseHeader]] = ResponseHeader
    subtopology_id: str = field(metadata={"kafka_type": "string"})
    """The subtopology identifier."""
    partitions: tuple[i32, ...] = field(metadata={"kafka_type": "int32"}, default=())
    """The partitions of the input topics processed by this member."""


@dataclass(frozen=True, slots=True, kw_only=True)
class Endpoint:
    __type__: ClassVar = EntityType.nested
    __version__: ClassVar[i16] = i16(0)
    __flexible__: ClassVar[bool] = True
    __api_key__: ClassVar[i16] = i16(88)
    __header_schema__: ClassVar[type[ResponseHeader]] = ResponseHeader
    host: str = field(metadata={"kafka_type": "string"})
    """host of the endpoint"""
    port: u16 = field(metadata={"kafka_type": "uint16"})
    """port of the endpoint"""


@dataclass(frozen=True, slots=True, kw_only=True)
class TopicPartition:
    __type__: ClassVar = EntityType.nested
    __version__: ClassVar[i16] = i16(0)
    __flexible__: ClassVar[bool] = True
    __api_key__: ClassVar[i16] = i16(88)
    __header_schema__: ClassVar[type[ResponseHeader]] = ResponseHeader
    topic: TopicName = field(metadata={"kafka_type": "string"})
    """topic name"""
    partitions: tuple[i32, ...] = field(metadata={"kafka_type": "int32"}, default=())
    """partitions"""


@dataclass(frozen=True, slots=True, kw_only=True)
class EndpointToPartitions:
    __type__: ClassVar = EntityType.nested
    __version__: ClassVar[i16] = i16(0)
    __flexible__: ClassVar[bool] = True
    __api_key__: ClassVar[i16] = i16(88)
    __header_schema__: ClassVar[type[ResponseHeader]] = ResponseHeader
    user_endpoint: Endpoint
    """User-defined endpoint to connect to the node"""
    active_partitions: tuple[TopicPartition, ...]
    """All topic partitions materialized by active tasks on the node"""
    standby_partitions: tuple[TopicPartition, ...]
    """All topic partitions materialized by standby tasks on the node"""


@dataclass(frozen=True, slots=True, kw_only=True)
class StreamsGroupHeartbeatResponse:
    __type__: ClassVar = EntityType.response
    __version__: ClassVar[i16] = i16(0)
    __flexible__: ClassVar[bool] = True
    __api_key__: ClassVar[i16] = i16(88)
    __header_schema__: ClassVar[type[ResponseHeader]] = ResponseHeader
    throttle_time: i32Timedelta = field(metadata={"kafka_type": "timedelta_i32"})
    """The duration in milliseconds for which the request was throttled due to a quota violation, or zero if the request did not violate any quota."""
    error_code: ErrorCode = field(metadata={"kafka_type": "error_code"})
    """The top-level error code, or 0 if there was no error"""
    error_message: str | None = field(metadata={"kafka_type": "string"}, default=None)
    """The top-level error message, or null if there was no error."""
    member_id: str = field(metadata={"kafka_type": "string"})
    """The member id is always generated by the streams consumer."""
    member_epoch: i32 = field(metadata={"kafka_type": "int32"})
    """The member epoch."""
    heartbeat_interval: i32Timedelta = field(metadata={"kafka_type": "timedelta_i32"})
    """The heartbeat interval in milliseconds."""
    acceptable_recovery_lag: i32 = field(metadata={"kafka_type": "int32"})
    """The maximal lag a warm-up task can have to be considered caught-up."""
    task_offset_interval: i32Timedelta = field(metadata={"kafka_type": "timedelta_i32"})
    """The interval in which the task changelog offsets on a client are updated on the broker. The offsets are sent with the next heartbeat after this time has passed."""
    status: tuple[Status, ...] | None
    """Indicate zero or more status for the group."""
    active_tasks: tuple[TaskIds, ...] | None
    """Assigned active tasks for this client. Null if unchanged since last heartbeat."""
    standby_tasks: tuple[TaskIds, ...] | None
    """Assigned standby tasks for this client. Null if unchanged since last heartbeat."""
    warmup_tasks: tuple[TaskIds, ...] | None
    """Assigned warm-up tasks for this client. Null if unchanged since last heartbeat."""
    endpoint_information_epoch: i32 = field(metadata={"kafka_type": "int32"})
    """The endpoint epoch set in the response"""
    partitions_by_user_endpoint: tuple[EndpointToPartitions, ...] | None
    """Global assignment information used for IQ. Null if unchanged since last heartbeat."""
