"""
Generated from AlterUserScramCredentialsRequest.json.
"""
from dataclasses import dataclass
from dataclasses import field
from typing import ClassVar

from kio.schema.primitive import i8
from kio.schema.primitive import i32


@dataclass(frozen=True, slots=True, kw_only=True)
class ScramCredentialDeletion:
    __flexible__: ClassVar[bool] = True
    name: str = field(metadata={"kafka_type": "string"})
    """The user name."""
    mechanism: i8 = field(metadata={"kafka_type": "int8"})
    """The SCRAM mechanism."""


@dataclass(frozen=True, slots=True, kw_only=True)
class ScramCredentialUpsertion:
    __flexible__: ClassVar[bool] = True
    name: str = field(metadata={"kafka_type": "string"})
    """The user name."""
    mechanism: i8 = field(metadata={"kafka_type": "int8"})
    """The SCRAM mechanism."""
    iterations: i32 = field(metadata={"kafka_type": "int32"})
    """The number of iterations."""
    salt: bytes = field(metadata={"kafka_type": "bytes"})
    """A random salt generated by the client."""
    salted_password: bytes = field(metadata={"kafka_type": "bytes"})
    """The salted password."""


@dataclass(frozen=True, slots=True, kw_only=True)
class AlterUserScramCredentialsRequest:
    __flexible__: ClassVar[bool] = True
    deletions: tuple[ScramCredentialDeletion, ...]
    """The SCRAM credentials to remove."""
    upsertions: tuple[ScramCredentialUpsertion, ...]
    """The SCRAM credentials to update/insert."""
